apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service-loadbalancer
spec:
  selector:
    app: nodejs-app
  ports:
    - name: http
      port: 80       
      targetPort: 3000 
  type: LoadBalancer  